# Generated by Django 3.0.4 on 2020-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
